version: '3'
services:
  naming-server:
    container_name: naming-server
    build:
      context: eureka-naming-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - shopbiz-network

  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      STORAGE_TYPE: mem
    ports:
      - "9411:9411"
    restart: always
    networks:
      - shopbiz-network

  zuul-api-gateway:
    container_name: zuul-api-gateway
    build:
      context: zuul-proxy
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    restart: always
    depends_on:
      - naming-server
      - zipkin-server
    networks:
      - shopbiz-network

  coupon-service:
    container_name: coupon-service
    build:
      context: coupon-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - naming-server
      - zipkin-server
      - mp-mongodb
    networks:
      - shopbiz-network

  shopbiz-ui:
    container_name: shopbiz-ui
    build: ./shopbiz-ui
    ports:
      - "80:80"
    depends_on:
      - shopbiz-api
    networks:
      - shopbiz-network

  shopbiz-api:
    container_name: shopbiz-api
    restart: always
    build:
      context: shopbiz-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    #command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
    depends_on:
      - coupon-service
      - naming-server
      - zipkin-server
      - mp-mysql
      - rabbitmq
      - mp-redis
    networks:
      - shopbiz-network

  order-service:
    container_name: order-service
    restart: always
    build:
      context: order-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - shopbiz-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - shopbiz-network

  mp-redis:
    container_name: mp-redis
    image: redis:5
    ports:
      - "6379:6379"
    restart: always
    networks:
      - shopbiz-network

  mp-mongodb:
    container_name: mp-mongodb
    image: mongo:3.6
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      - shopbiz-network

  mp-mysql:
    container_name: mp-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: shopbiz
      MYSQL_ROOT_PASSWORD: taco
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    networks:
      - shopbiz-network

volumes:
  mongo-data:
  mysql-data:
networks:
  shopbiz-network:
